Ticket5363: Check GitHub urls
ISISComputingGroup/ibex_wiki_checker pull request #11
Opened 2020-09-07 11:06 UTC by rerpha

Originally the solution for ticket 5363 was to use the Github API to resolve links on the wiki that directed to other wiki pages, however the API [cannot be used to do this](https://github.community/t/api-for-repositorys-wiki/902)

The workaround was unexcluding Github pages from the link checker, and add a conditional to check whether the Github links were to one of our Wikis. if this is the case, compare against the local cloned copies rather than trying to ping the Github URL (the same way relative wiki page links are handled). This should drastically limit the amount of calls to Github pages and therefore make it less likely for the tests to fail because of the limit.

For ticket ISISComputingGroup/IBEX#5363

2020-09-07 16:11 UTC, Alexandru-Dascalu commented on run_tests.py
too many lines left

2020-09-08 10:58 UTC, Alexandru-Dascalu requested changes
It is good work, and the code looks like it should work, but I edited a link on our dev wiki so it is broken, but this did not pick it up. Moreover, it tried to directly check the validity of some of some github links to our wikis and failed due to Github call limiting.

2020-09-08 10:58 UTC, Alexandru-Dascalu commented on tests/page_tests.py
> +                if get_url_basename(link) == "github.com" and any([f"{wiki.name}/wiki" in link for wiki in WIKI_INCLUDELIST]):
The Wiki Checker currently runs with Python 2.7, which does not support format strings. Please use a different way to format strings.

2020-09-08 10:58 UTC, Alexandru-Dascalu commented on tests/page_tests.py
> +                failure = try_to_connect(link, session)
I think the code would look cleaner and would make the logic clearer if you put the connection failure check within an else statement. It makes it more clear that the algorithm is to check if the link is a full link to one of our wiki pages, and if not it is an external github link and we want to check if we can connect to it.

2020-09-08 10:58 UTC, Alexandru-Dascalu commented on tests/page_tests.py
>              # Also White list github links from checking for the moment if they are valid as GitHub limits
This comment should be amended because now github links are no longer ignored

2020-09-08 10:58 UTC, Alexandru-Dascalu commented on tests/page_tests.py
> +        def check_link(link, session, filenames, folders):
Could you please add a pydoc for this method and comments for conditional statements inside it, so the algorithm is more clear?

2020-09-08 10:58 UTC, Alexandru-Dascalu commented on tests/page_tests.py
> +                return "Could not follow page link {}".format(link)
I like that you renamed some variables to more sensible names.

2020-09-14 08:42 UTC, RaiBishal approved these changes

2020-09-14 08:42 UTC, merged