Ticket4507 check page links are correct
ISISComputingGroup/ibex_wiki_checker pull request #3
Opened 2019-07-29 10:59 UTC by ChrisColeExpControl

As per ticket https://github.com/ISISComputingGroup/IBEX/issues/4507

2019-08-08 15:18 UTC, Tom-Willemsen requested changes
Looks pretty good - functionality mostly there in terms of checking links. I've left a handful of comments in the code on some style points.

The tests now seem to take an long time. Given that all of the web requests happen independently from each other and we just want to return essentially a boolean from each one, can we use `concurrent.Futures` to do the web requests in parallel & save on time? If you need some help setting this up give me a shout - I believe there is a backport to python 2, otherwise we could just use plain `threading`.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +    def test_GIVEN_a_page_IF_it_contains_urls_WHEN_url_loaded_THEN_response_is_http_ok(self):
This method is now rather long - can it be split up by using a couple of helper functions?

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +        bracketed_urls = re.findall(r'\([^\)]*?\[.+?\]\(([\S^#]+)\)\)', text)
More explanation of these regexes is needed.

Regex tends to get very unreadable very quickly, especially long ones like this. Consider:
- Adding more commenting explaning what it is matching/not matching and why
- Splitting the regex into multiple (named) sub-patterns which are more understandable, and then joining those sub-patterns into a larger regex at the end.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +        urls = [url for url in urls if url[:-1] not in bracketed_urls] + bracketed_urls
An explanation of what this does would be useful.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +            self.fail("FAILED TO OPEN {}".format(self.page))
This would give us a bit more information about what failed - otherwise we lose the exception trace:

```suggestion
            self.fail("FAILED TO OPEN {} because {} : {}".format(self.page, e.__class__.__name__, e))
```

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +        except Exception:
```suggestion
        except Exception as e:
```

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +        filenames = [os.path.basename(f)[:-3].lower() for f in self.all_pages]
`-3` is a magic number. I guess this is really `-len(".md")` to strip off the filename extension.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +        folders = next(os.walk(self.wiki_dir))[1]
Can you use `os.listdir()` here?

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +            lambda url: url.split("/")[0] in folders
I don't think this should be a "skip" condition - this matches any page which is in a valid folder (even if the page itself isn't valid)

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +                            "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:53.0) Gecko/20100101 Firefox/53.0"}
Quick comment about why this header was chosen / why it is needed would be beneficial.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +                url = url.split("#")[0].strip()
👍

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +                    url = "http://"+url
Our [python coding guidelines](https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Python-conventions#use-format-to-construct-strings-from-values) suggest using `.format` rather than `+` to build strings.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/page_tests.py
> +                elif skip_conditions[4](url) and not (os.path.isfile(os.path.join(self.wiki_dir, url))
Indexing into a list with magic numbers (`4`) like this is brittle. Instead, we should use a named function which we add to the list but can refer to by name here.

2019-08-08 15:18 UTC, Tom-Willemsen commented on tests/shadow_mirroring_tests.py
> +        self.page = wiki_info[0]
Add a docstring to this function that says what datatype `wiki_info` should have - it's not clear what `wiki_info[0]` represents.

2019-08-08 15:18 UTC, Tom-Willemsen commented on urls.txt
> +
would this file be better named `ignored_urls` or similar?

2019-08-13 10:58 UTC, ChrisColeExpControl commented on tests/page_tests.py
> +                elif skip_conditions[4](url) and not (os.path.isfile(os.path.join(self.wiki_dir, url))
removed that item from the list, now checked seperately (made another part of the code easier anyway)

2019-08-13 10:59 UTC, ChrisColeExpControl commented on tests/page_tests.py
> +                    url = "http://"+url
I'll remeber that going forwards (hadn't found that page before, thanks!)

2019-08-13 11:00 UTC, ChrisColeExpControl commented on tests/page_tests.py
> +        filenames = [os.path.basename(f)[:-3].lower() for f in self.all_pages]
now using os.splitext to do this instead.

2019-08-13 11:02 UTC, ChrisColeExpControl commented on tests/page_tests.py
> +            lambda url: url.split("/")[0] in folders
This is only being skipped for http requests, links that pass only this one are checked further on to see if their file actually exists.

2019-08-13 11:05 UTC, ChrisColeExpControl commented on tests/page_tests.py
> +        folders = next(os.walk(self.wiki_dir))[1]
At that point I only wanted to find the folders, as most of our wikis store non-md files within forlders. Looking at the structure of the user manual however, I've decided to just look at everything in the folder instead.

2019-08-13 11:11 UTC, ChrisColeExpControl commented
While performing the rework I noticed that I hadn't added the ability to find links in the .rest format, which our user manual uses, so I added this alongside the fixes. Additionally, the spelling checker was being given a set of files of only one format per wiki to check (.md for IBEX and developer manual, .rest for user manual), when there were pages in both formats in two of our wikis. I've changes this so that it no longer needs to be told which format to load, instead it loads all files in both formats.
Thanks for the suggestion of connections.futures, I hadn't thought of threading. Tests now take roughly 7 minutes total.

2019-08-14 09:52 UTC, Tom-Willemsen approved these changes
Code now looks more readable and performance is better, thanks.

2019-08-14 09:52 UTC, merged